MARCToolApp/Models/MarcCode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MARCToolApp.Models
{
    public class MarcCode
    {
        public string Code { get; set; }
        public MARCCodeTableMap MARCCodeTableMap { get; set; }
    }
}

MARCToolApp/Models/MarcCodeTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MARCToolApp.Models
{
    //public class MARCCodeTable
    //{
    //    public int MarcRecordFormatId { get; set; }
    //    public int TagNumber { get; set; }
    //    public string Subfield { get; set; }
    //    public int? PositionNumber { get; set; }
    //    public int MARCCodeTableId { get; set; }
    //    //public string MARCCodeTableName { get; set; }
    //    public string TableName { get; set; }
    //    //public string MARCCodeTableDisplay { get; set; }
    //}
}

MARCToolApp/Controllers/MarcCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MARCToolApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using MARCToolApp.Models.Enums;
using MARCToolApp.Repositories.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MARCToolApp.Controllers
{
    [Authorize]
    public class MarcCodeController : Controller
    {
        #region Private Members
        private IRepositorySourceCode _repoSourceCode;
        #endregion

        public MarcCodeController(IRepositorySourceCode repoSourceCode)
        {
            _repoSourceCode = repoSourceCode;
        }

#region Actions
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var list = await Get();
            return View(list);
        }
        // GET: /<controller>/
        public async Task<IActionResult> Add(int id)
        {
            try
            {
                var sourceCode = await GetSourceCode(id);

                var tables = await Get(sourceCode, true, false);

                sourceCode.CodeTables = tables.ToList();

                if (tables.Count() > 0)
                {
                    foreach (var colum in tables.First().Columns)
                    {
                        if (colum.Name.ToUpper() == IgnoredColumn.Code.ToString().ToUpper())
                        {
                            try
                            {
                                sourceCode.SelectedCodeMaxLength = int.Parse(colum.MaxLength);
                            }
                            catch
                            {
                                sourceCode.SelectedCodeMaxLength = 10;
                            }
                            break;
                        }
                    }
                }

                return View(sourceCode);
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult AddWithModel(SourceCodeModel sourceCode)
        {
            if (sourceCode.CodeTables == null)
            {
                throw new Exception("Invalid model data. SourceCodeModel.CodeTables is null");
            }

            if (string.IsNullOrWhiteSpace(sourceCode.SelectedCode))
            {
                throw new Exception("Invalid model data. SourceCodeModel.SelectedCode is invalid");
            }

            //if (ModelState.IsValid)
            //{
                var statement = "";
                foreach (var table in sourceCode.CodeTables)
                {
                    var sql = FormatInsertSql(table, sourceCode.SelectedCode);

                    statement += sql;
                }

                //return RedirectToAction("Script",
                //    new
                //    {
                //        sourceCodeName = sourceCode.CodeName,
                //        sqlStatement = statement,
                //        tables = new List<TableModel>(sourceCode.CodeTables)
                //    });

                ViewData["SourceCodeName"] = sourceCode.CodeName;
                ViewData["SqlStatement"] = statement;

                return View("Script");
            //}

            //throw new Exception($"Invalid ModelState. {ModelState.ToString()}");
        }
        // GET: /<controller>/
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var sourceCode = await GetSourceCode(id);

                var tables = await Get(sourceCode, true, true);

                var viewTables = new List<MarcCodeEditViewTabelModel>();
                var i = 0;
                foreach (var table in tables)
                {
                    viewTables.Add(new MarcCodeEditViewTabelModel
                    {
                        TableModel = table,
                        TableIndex = i
                    });
                    i++;
                }

                ViewData["SourceCodeName"] = sourceCode.CodeName;
                return View(viewTables);
            }
            catch
            {
                return View();
            }
        }
        public async Task<ActionResult> GetTableValues(string tablename, int tableid, int tableindex, string code)
        {
            var viewTable = new MarcCodeEditViewTabelModel { TableIndex = tableindex };

            viewTable.TableModel = await _repoSourceCode.GetRowValueByCode(tablename, tableid, code);

            return PartialView("_EditTable", viewTable);
        }
        [HttpPost]
        public ActionResult EditWithModel(List<TableModel> codeTables, string sourceCodeName)
        {
            var statement = "";

            foreach(var table in codeTables)
            {
                statement += FormatUpdateSql(table);
            }

            ViewData["SourceCodeName"] = sourceCodeName;
            ViewData["SqlStatement"] = statement;

            return View("Script");
        }
        // GET: /<controller>/
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var sourceCode = await GetSourceCode(id);
                var tables = await Get(sourceCode, false, true);

                ViewData["SourceCodeName"] = sourceCode.CodeName;

                return View(tables);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public ActionResult DeleteWithModel(List<TableModel> CodeTables, string sourceCodeName)
        {
            if (CodeTables == null)
            {
                throw new Exception("Invalid model data. SourceCodeModel.CodeTables is null");
            }

            var sql_statement = "";
            try
            {
                foreach (var table in CodeTables)
                {
                    sql_statement += FormatDeleteSql(table);
                }
            }
            catch
            {
                sql_statement = Views.Resource.ErrorScriptFail;
            }

            ViewData["SourceCodeName"] = sourceCodeName;
            ViewData["SqlStatement"] = sql_statement;

            return View("Script");
        }
        #endregion
        #region Private Methods
        private async Task<SourceCodeModel> GetSourceCode(int id)
        {
            var list = await Get();
            var sourceCode = list.Single(c => c.CodeId == id);
 
            return sourceCode;
        }
        private async Task<IEnumerable<TableModel>> Get(SourceCodeModel sourceCode, bool loadColumns, bool loadCodes)
        {
            return await _repoSourceCode.Get(sourceCode, loadColumns, loadCodes);

            //List<TableModel> tables = new List<TableModel>();

            //if (sourceCode.Tags == null || sourceCode.Tags.Count == 0)
            //{
            //    return tables;
            //}

            //if (_MarcTables == null || _MarcTables.Count() == 0)
            //{
            //    _MarcTables = await LoadTablesBySourceCode(sourceCode);
            //}

            //using (var conn = new SqlConnection(_connectionString))
            //{
            //    conn.Open();

            //    foreach (var table in _MarcTables)
            //    {
            //        if (string.IsNullOrEmpty(table.MARCCodeTable))
            //        {
            //            continue;
            //        }

            //        var columns = (loadColumns ? LoadColumns(table.MARCCodeTable, conn) : null);
            //        var codes = (loadCodes ? (new List<string>(LoadCodesByTableId(table.MARCCodeTableId, conn))) : null);

            //        tables.Add(new TableModel
            //        {
            //            MARCCodeTable = table.MARCCodeTable,
            //            MARCCodeTableId = table.MARCCodeTableId,
            //            MARCCodeTableDisplay = table.MARCCodeTableDisplay,
            //            Columns = columns,
            //            Codes = codes
            //        });
            //    }
            //}

            //return tables;
        }
        private async Task<IEnumerable<SourceCodeModel>> Get()
        {
            return await _repoSourceCode.Get();
        }
        #endregion  
        #region Helper - Format SQL
        private string FormatInsertSql(TableModel table, string newCode)
        {
            string sql = "";

            sql = $"if exists(select * from Polaris.{table.MARCCodeTable} with (nolock) where Code = N'{newCode}') {Environment.NewLine}" +
                $"\tdelete from {table.MARCCodeTable} where Code = N'{newCode}';{Environment.NewLine}";

            var columns = "";
            var values = "";
            foreach (var column in table.Columns)
            {
                columns += (string.IsNullOrEmpty(columns) ? "" : ", ") + column.Name;

                // apply default values to predefined columns
                var value = (column.Name == IgnoredColumn.LocallyDefinedFlag.ToString() ||
                    column.Name == IgnoredColumn.ObsoleteFlag.ToString() || column.Name == IgnoredColumn.ModifiedFlag.ToString()) ? "0" :
                        (column.Name == IgnoredColumn.Code.ToString() ? newCode : column.Value);

                if (!string.IsNullOrEmpty(value) && (column.Type.ToLower() == "nvarchar" || column.Type.ToLower() == "nchar"))
                {
                    // N'' prefix and quote string/char values 
                    value = NormalizeSqlStringValue(value);
                    value = $"N'{value}'";
                }
                else if (!string.IsNullOrEmpty(value) && (column.Type.ToLower() == "varchar" || column.Type.ToLower() == "char"))
                {
                    // '' quote string/char values

MARCToolApp/Views/MarcCode/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MARCToolApp.Models.ViewModels
@model SourceCodeModel
@{
    ViewBag.Title = @Resource.ButtonAdd + " - " + Model.CodeName;
}
<div class="container">
    <form action="@Url.Action("AddWithModel", "MarcCode")" id="formAdd" method="post" enctype="multipart/form-data" target="_blank">
        @Html.Hidden("sourceCode.CodeId", Model.CodeId)
        @Html.Hidden("sourceCode.CodeName", Model.CodeName)

        <p></p>
        <div class="row">
            <h4>@ViewBag.Title</h4>
        </div>
        @if (Model.CodeTables.Count > 0)
        {
            <div class="row">
                <div class="col-sm-2" style="margin-top:0.75em;margin-bottom:0.5em;text-align:right;">@Html.Label($"{Resource.LabelNewCode}")</div>
                <div class="col-sm-2" style="margin-top:0.25em;margin-bottom:0.5em;">
                    @Html.TextBox("sourceCode.SelectedCode", Model.SelectedCode, new { @id = "txtNewCode", @placeholder = $"{Resource.LabelNewCode.ToLower()}", @class = "form-control", @autofocus = "autofocus", @maxlength = $"{Model.SelectedCodeMaxLength}", @required = "required" })
                </div>
            </div>
        }

        @for (int i = 0; i < Model.CodeTables.Count; i++)
        {
            @Html.Hidden("sourceCode.CodeTables[" + i + "].MARCCodeTable", Model.CodeTables[i].MARCCodeTable)
            @Html.Hidden("sourceCode.CodeTables[" + i + "].MARCCodeTableId", Model.CodeTables[i].MARCCodeTableId)
            @Html.Hidden("sourceCode.CodeTables[" + i + "].MARCCodeTableDisplay", Model.CodeTables[i].MARCCodeTableDisplay)

            <div class="panel panel-primary">
                <div class="panel-heading" style="background-color:transparent">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@Model.CodeTables[i].MARCCodeTable">
                        @Html.DisplayFor(model => Model.CodeTables[i].MARCCodeTable)
                    </a>
                </div>
                <div id="collapse-@Model.CodeTables[i].MARCCodeTable" class="panel-collapse collapse in">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th style="width: 35%;">@Resource.TableHeaderColumn</th>
                                <th>@Resource.TableHeaderValue</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{var col = 0;}
                            @foreach (var column in Model.CodeTables[i].Columns)
                            {
                                @Html.Hidden("sourceCode.CodeTables[" + i + "].Columns[" + col + "].Name", column.Name)
                                @Html.Hidden("sourceCode.CodeTables[" + i + "].Columns[" + col + "].Type", column.Type)

                                @if (!column.Hide)
                                {
                                    var htmlAttr = new Dictionary<string, object>();
                                    htmlAttr.Add("class", "form-control");
                                    htmlAttr.Add("placeholder", column.DataType);
                                    htmlAttr.Add("maxlength", column.MaxLength);
                                    if (!column.AllowNull)
                                    {
                                        htmlAttr.Add("required", "required");
                                    }
                                    if (column.Type == "bit")
                                    {
                                        htmlAttr.Add("max", 1);
                                        htmlAttr.Add("min", 0);
                                        htmlAttr.Add("type", "number");
                                    }

                                    <tr>
                                        <td>
                                            @Html.DisplayFor(m => column.Name)
                                        </td>
                                        <td>
                                            @Html.TextBox("sourceCode.CodeTables[" + i + "].Columns[" + col + "].Value", column.Value, htmlAttr)
                                        </td>
                                    </tr>
                                }

                                col++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
                                }
        <div class="row">
            <div class="col-sm-6">@Html.ActionLink(Resource.FooterBackToList, "Index")</div>
            @if (Model.CodeTables.Count > 0)
            {
                <div class="col-sm-6" style="text-align:right;"><input class="btn btn-primary" type="submit" value="@Resource.ButtonGenerateScript" /></div>
            }
        </div>
    </form>

</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Code Added</h4>
            </div>
            <div class="modal-body">
                <p>New @ViewBag.SourceCodeName code is added to codes tables.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
        $(function () {
            $("#submit").click(function () {
                document.forms[0].submit();
                return false;
            });
        });
</script>
    

MARCToolApp/Views/MarcCode/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MARCToolApp.Models.ViewModels
@model IEnumerable<TableModel>
@{
    ViewBag.Title = @Resource.ButtonDelete + " - " + ViewBag.SourceCodeName;
}
<div class="container">
    <h3>@ViewBag.Title</h3>
    <form action="@Url.Action("DeleteWithModel", "MarcCode", Model)" id="formDelete" method="post" enctype="multipart/form-data" target="_blank">
        @Html.Hidden("sourceCodeName", $"{ViewBag.SourceCodeName}")

        <div class="form-horizontal">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@Resource.TableHeaderTable</th>
                        <th>@Resource.TableHeaderCode</th>
                    </tr>
                </thead>
                <tbody>
                    @{var index = 0; }
                    @foreach (var table in @Model)
                    {
                        @Html.Hidden("CodeTables[" + index+ "].MARCCodeTable", table.MARCCodeTable);
                        @Html.Hidden("CodeTables[" + index + "].Code", table.Codes[0]);

                        <tr>
                            <td>
                                @Html.DisplayFor(model => table.MARCCodeTable)
                            </td>
                            <td>
                                @Html.DropDownList("CodeTables[" + index + "].Codes[0]", new SelectList(table.Codes), Resource.DropdownSelectCodeDelete, 
                                    new { @class = "form-control" })
                            </td>
                        </tr>

                        index ++;
                    }
                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-6">@Html.ActionLink($"{Resource.FooterBackToList}", "Index")</div>
                <div class="col-sm-6" style="text-align:right;"><input class="btn btn-primary" type="submit" value="@Resource.ButtonGenerateScript" /></div>
            </div>
        </div>
    </form>
</div>

MARCToolApp/Views/MarcCode/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MARCToolApp.Models.ViewModels
@model IEnumerable<MarcCodeEditViewTabelModel>
@{
    ViewBag.Title = @Resource.ButtonEdit + " - " + ViewBag.SourceCodeName;
}
<div class="container">
    <h3>@ViewBag.Title</h3>
    <form action="@Url.Action("EditWithModel", "MarcCode")" id="formDelete" method="post" enctype="multipart/form-data" target="_blank">
        @Html.Hidden("sourceCodeName", ViewData["SourceCodeName"])

        @{ var i = 0; }
        <div class="panel-group">
            @foreach (var table in Model)
            {
                @Html.Hidden("codeTables[" + i + "].MARCCodeTable", table.TableModel.MARCCodeTable)
                @Html.Hidden("codeTables[" + i + "].MARCCodeTableId", table.TableModel.MARCCodeTableId)
                @Html.Hidden("codeTables[" + i + "].MARCCodeTableDisplay", table.TableModel.MARCCodeTableDisplay)

                var open = i == 0 ? "in" : "";
                <div class="panel panel-primary">
                    <div class="panel-heading" style="background-color:transparent">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@table.TableModel.MARCCodeTableId">@Html.DisplayFor(model => table.TableModel.MARCCodeTable)</a>
                    </div>
                    <div id="collapse-@table.TableModel.MARCCodeTableId" class="panel-collapse collapse @open">
                        @Html.Partial("_EditTable", table)
                    </div>
                </div>

                i++;
            }
        </div>
        <div class="row">
            <div class="col-sm-6">@Html.ActionLink($"{Resource.FooterBackToList}", "Index")</div>
            <div class="col-sm-6" style="text-align:right;"><input class="btn btn-primary" type="submit" value="@Resource.ButtonGenerateScript" /></div>
        </div>
        </form>
</div>

@section Scripts 
{
    <script>
        function RefreshTable(code, tablename, tableid, tableindex) {
            var div = '#collapse-' + tableid;
            var url = '@(Url.Action("GetTableValues", "MarcCode"))?code=' + code + '&tablename=' + tablename + '&tableid=' + tableid + '&tableindex=' + tableindex;
            $(div).load(url);
        }
    </script>
}

MARCToolApp/Views/MarcCode/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@using MARCToolApp.Models.ViewModels
@model IEnumerable<SourceCodeModel>

@{
    ViewBag.Title = "Source Code List";
}

<div class="container">
    <h2>@ViewBag.Title</h2>
    @*<p><strong>Note:</strong> The <strong>data-parent</strong> attribute makes sure that all collapsible elements under the specified parent will be closed when one of the collapsible item is shown.</p>*@
    <div class="panel-group" id="accordion">
        @foreach (var code in @Model)
        {
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@code.CodeId">
                            @Html.DisplayFor(model => code.CodeName)
                        </a>
                    </h4>
                </div>
                <div id="collapse-@code.CodeId" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>MARC Record Format</th>
                                    <th>TagNumber</th>
                                    <th>Subfiled</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var tag in code.Tags)
                {
                                    <tr>
                                        <td>
                                            @tag.Format
                                        </td>
                                        <td>@tag.Tag </td>
                                        <td>$ @tag.Subfield</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="btn-group">
                        <div class="col-md-4">
                            <a class="btn btn-default" asp-action="Add" asp-route-id="@code.CodeId"><i class="glyphicon glyphicon-plus"> @Resource.ButtonAdd</i></a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default" asp-action="Edit" asp-route-id="@code.CodeId"><i class="glyphicon glyphicon-edit"> @Resource.ButtonEdit</i></a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default" asp-action="Delete" asp-route-id="@code.CodeId"><i class="glyphicon glyphicon-trash"> @Resource.ButtonDelete</i></a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Team.TeamId }) |
    @Html.ActionLink($"{Resource.FooterBackToList}", "Index")*@
</p>

MARCToolApp/Views/MarcCode/Script.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "SQL Script Generated to " + ViewBag.SourceCodeName;

    var statement = $"FAILED TO GENERATE A SQL ALTER SCRIPT!!!";
    statement = ViewBag.SqlStatement;
}
<div class="container">
    <h4>@ViewBag.Title</h4>
    
    @Html.TextArea("Statement", @statement, 50, 1, 
        new {@class="form-control", @readonly="true", @style= "resize:none; overflow:auto;" })
</div>

MARCToolApp/Views/MarcCode/_EditTable.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MarcCodeEditViewTabelModel
@{
}
    @Html.Hidden("tablename", Model.TableModel.MARCCodeTable)
    @Html.Hidden("tableid", Model.TableModel.MARCCodeTableId)
    @Html.Hidden("tableindex", Model.TableIndex)

<table class="table table-striped">
    <thead>
        <tr>
            <th style="width: 35%;">@Resource.TableHeaderColumn</th>
            <th>@Resource.TableHeaderValue</th>
        </tr>
    </thead>
    <tbody>
        @{ var col = 0; }
        @foreach (var column in Model.TableModel.Columns)
        {
            @Html.Hidden("codeTables[" + Model.TableIndex + "].Columns[" + col + "].Type", column.Type)
            @Html.Hidden("codeTables[" + Model.TableIndex + "].Columns[" + col + "].Name", column.Name)

            <tr>
                <td>
                    @Html.DisplayFor(model => column.Name)
                </td>
                <td>
                    @if (column.Name == "Code")
                    {
                            @Html.Hidden("codeTables[" + Model.TableIndex + "].Codes[0]", column.Value??"")

                        @Html.DropDownList("codeTables[" + Model.TableIndex + "].Columns[" + col + "].Value",
                            new SelectList(Model.TableModel.Codes),
                            string.IsNullOrEmpty(column.Value) ? Resource.DropdownSelectCodeUpdate : column.Value,
                            new { @class = "form-control",
                                @onchange = "RefreshTable($(this).val(), '" + Model.TableModel.MARCCodeTable + "', '" + Model.TableModel.MARCCodeTableId + "', '" + Model.TableIndex + "');",
                            })
                    }
                    else
                    {
                        var htmlAttr = new Dictionary<string, object>();
                        htmlAttr.Add("class", "form-control");
                        htmlAttr.Add("maxlength", column.MaxLength);
                        if (column.AllowNull)
                        {
                            htmlAttr.Add("placeholder", column.DataType);
                        }
                        else
                        {
                            htmlAttr.Add("placeholder", $"{column.DataType} (required)");
                            //htmlAttr.Add("required", "required");
                        }

                        if (column.Type == "bit")
                        {
                            htmlAttr.Add("max", 1);
                            htmlAttr.Add("min", 0);
                            htmlAttr.Add("type", "number");
                        }

                        @Html.TextBox("codeTables[" + Model.TableIndex + "].Columns[" + col + "].Value", column.Value??"", htmlAttr)
                    }
                </td>
            </tr>

            col++;
        }
    </tbody>
</table>